name: Autophagy
options:
  bundleIdPrefix: cloud.buggygames.autophagy
  deploymentTarget:
    iOS: "17.0"
    watchOS: "10.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  createIntermediateGroups: true

schemes:
  Autophagy:
    build:
      targets:
        Autophagy: all
        AutophagyWidget: all
        Autophagy Watch App: all
        AutophagyWatchWidget: all
    run:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

settings:
  base:
    DEVELOPMENT_TEAM: 4YN4S8KBCP
    CODE_SIGN_STYLE: Automatic
    GENERATE_INFOPLIST_FILE: YES

targets:
  Autophagy:
    type: application
    platform: iOS
    sources:
      - path: Autophagy
      - path: Shared
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: Autophagy
        INFOPLIST_KEY_UILaunchStoryboardName: LaunchScreen
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_ITSAppUsesNonExemptEncryption: NO
        PRODUCT_BUNDLE_IDENTIFIER: cloud.buggygames.autophagy.app
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0
    entitlements:
      path: Autophagy/Autophagy.entitlements
      properties:
        com.apple.security.application-groups:
          - group.cloud.buggygames.autophagy.app
        com.apple.developer.ubiquity-kvstore-identifier: $(TeamIdentifierPrefix)cloud.buggygames.autophagy.app
    dependencies:
      - target: AutophagyWidget
      - target: Autophagy Watch App

  Autophagy Watch App:
    type: application
    platform: watchOS
    sources:
      - path: Autophagy Watch App
      - path: Shared
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: Autophagy
        INFOPLIST_KEY_WKCompanionAppBundleIdentifier: cloud.buggygames.autophagy.app
        PRODUCT_BUNDLE_IDENTIFIER: cloud.buggygames.autophagy.app.watchkitapp
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0
    entitlements:
      path: Autophagy Watch App/AutophagyWatch.entitlements
      properties:
        com.apple.security.application-groups:
          - group.cloud.buggygames.autophagy.app
        com.apple.developer.ubiquity-kvstore-identifier: $(TeamIdentifierPrefix)cloud.buggygames.autophagy.app
    dependencies:
      - target: AutophagyWatchWidget

  AutophagyWidget:
    type: app-extension
    platform: iOS
    sources:
      - path: AutophagyWidget
      - path: Shared/FastingState.swift
    info:
      path: AutophagyWidget/Info.plist
      properties:
        CFBundleDisplayName: Fasting Widget
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: cloud.buggygames.autophagy.app.widget
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0
    entitlements:
      path: AutophagyWidget/AutophagyWidgetExtension.entitlements
      properties:
        com.apple.security.application-groups:
          - group.cloud.buggygames.autophagy.app

  AutophagyWatchWidget:
    type: app-extension
    platform: watchOS
    sources:
      - path: AutophagyWatchWidget
      - path: Shared/FastingState.swift
    info:
      path: AutophagyWatchWidget/Info.plist
      properties:
        CFBundleDisplayName: Fasting Widget
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: cloud.buggygames.autophagy.app.watchkitapp.widget
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0
    entitlements:
      path: AutophagyWatchWidget/AutophagyWatchWidgetExtension.entitlements
      properties:
        com.apple.security.application-groups:
          - group.cloud.buggygames.autophagy.app
